import './swiper';
import './js/Api/MainAPI';
import './js/render-categories';
import './js/search-form';
import './js/render-recipes-list';
import './js/header/mobile-menu';
import './js/header/theme-switcher';
import './js/modal-first';
import './js/popular';
import './js/pagination';
import './js/modal-rating';
import './js/registration';
import './js/favorite'
